name: Trigger DocGenerateAndPublish Workflow

on:
  workflow_dispatch:
    inputs:
      doc-branch-to-publish:
        description: 'Specify the branch used to generate the documentation (ex: v26.06)'
        default: 'master'
        type: string


jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run on dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: gh workflow run DocGenerateAndPublish --ref gen -f doc-version=${{ inputs.doc-branch-to-publish }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
