name: Trigger DocGenerateAndPublish Workflow

on:
  workflow_dispatch:
    inputs:
      script-branch:
        description: 'Specify the branch on which run the DocGenerateAndPublish acvtion'
        default: 'gen'
        type: string
  schedule:
    - cron: '0 6 * * 1'  # Every Monday morning
  push:
    branches:
      - master

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run on dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: gh workflow run DocGenerateAndPublish --ref ${{ inputs.script-branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run on push and nightly
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: gh workflow run DocGenerateAndPublish --ref gen
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
